stages:
- build-backend
- test-backend
- package-backend
- publish-backend
- deploy-backend

default:
  image: maven:3.9.5-amazoncorretto-17
  before_script:
  - cd ./code-quality-analyzer-backend
  tags:
  - vm3

build-backend-job:
  stage: build-backend
  script:
  - mvn compile

test-backend-job:
  stage: test-backend
  script:
  - mvn test

package-backend-job:
  stage: package-backend
  script:
  - mvn package
  artifacts:
    paths:
    - "./code-quality-analyzer-backend/target/*.jar"

publish-backend-job:
  image: docker:latest
  stage: publish-backend
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
  services:
  - docker:dind
  script:
  - docker --version
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS docker.io
  - docker build -t docker.io/$DOCKER_HUB_USER/$DOCKER_HUB_REPO:backend-$CI_COMMIT_SHORT_SHA
    .
  - docker push docker.io/$DOCKER_HUB_USER/$DOCKER_HUB_REPO:backend-$CI_COMMIT_SHORT_SHA
  
deploy-backend-job:
  image: alpine:latest
  stage: deploy-backend
  script:
  - chmod og= $ID_RSA
  - apk update && apk add openssh-client
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login
    -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS docker.io"
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull
    docker.io/$DOCKER_HUB_USER/$DOCKER_HUB_REPO:backend-$CI_COMMIT_SHORT_SHA"
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container
    rm -f my-backend-container || true"
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run
    -d -p 8080:8080 --restart=always --name backend-container docker.io/$DOCKER_HUB_USER/$DOCKER_HUB_REPO:backend-$CI_COMMIT_SHORT_SHA"
  environment:
    name: production
    url: http://csci5308vm3.research.cs.dal.ca:8080