.backend-common:
  image: maven:3.9.5-amazoncorretto-17
  before_script:
    - cd ./code-quality-analyzer-backend
  tags:
    - vm3

build-backend-job:
  stage: build
  extends: .backend-common
  script:
  - mvn compile

test-backend-job:
  stage: test
  extends: .backend-common
  needs: ["build-backend-job"]
  script:
  - mvn test

package-backend-job:
  stage: package
  extends: .backend-common
  needs: ["test-backend-job"]
  script:
  - mvn package
  artifacts:
    paths:
    - "./code-quality-analyzer-backend/target/*.jar"
  
deploy-backend-job:
  stage: deploy
  extends: .backend-common
  needs: ["package-backend-job"]
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "develop"
  script:
  - chmod og= $ID_RSA
  - apk update && apk add openssh-client
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "lsof -t -i :8080 | xargs -r kill"
  - scp -i $ID_RSA -o StrictHostKeyChecking=no target/code-quality-analyzer-backend-0.0.1-SNAPSHOT.jar $SERVER_USER@$SERVER_IP:/home/deployer/spring-boot-app/app.jar
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/deployer/spring-boot-app && bash -c 'setsid java -cp app.jar:\"./lib/DesigniteJava.jar\" org.springframework.boot.loader.JarLauncher > output.log 2>&1 &'"

  environment:
    name: production
    url: http://csci5308vm3.research.cs.dal.ca:8080