.backend-common:
  image: maven:3.9.5-amazoncorretto-17
  before_script:
    - cd ./code-quality-analyzer-backend
  tags:
    - vm3

1-build-backend-job:
  stage: build
  extends: .backend-common
  script:
  - mvn compile

1-test-backend-job:
  stage: test
  extends: .backend-common
  needs: ["1-build-backend-job"]
  script:
  - mvn test

1-package-backend-job:
  stage: package
  extends: .backend-common
  needs: ["1-test-backend-job"]
  script:
  - mvn package
  artifacts:
    paths:
    - "./code-quality-analyzer-backend/target/*.jar"
  
1-deploy-backend-job:
  stage: deploy
  extends: .backend-common
  needs: ["1-publish-backend-job"]
  image: alpine:latest
  script:
  - chmod og= $ID_RSA
  - apk update && apk add openssh-client
  - scp -i $ID_RSA -o StrictHostKeyChecking=no target/code-quality-analyzer-backend-0.0.1-SNAPSHOT.jar $SERVER_USER@$SERVER_IP:/home/student/app.jar
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/student && java -jar app.jar"
  environment:
    name: production
    url: http://csci5308vm3.research.cs.dal.ca:8080